In [23]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

In [2]:
file = r"C:\Users\shash\OneDrive\Desktop\solar_plant_power_forecasting\Renewable.csv\Renewable.csv"
data = pd.read_csv(file)
data

,Energy delta[Wh],GHI,temp,pressure,humidity,wind_speed,rain_1h,snow_1h,clouds_all,isSun,sunlightTime,dayLength,SunlightTime/daylength,hour,month
0,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.00,0,1
1,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.00,0,1
2,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.00,0,1
3,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.00,0,1
4,0,0.0,1.7,1020,100,5.2,0.0,0.0,100,0,0,450,0.00,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196771,118,23.7,18.6,1023,57,3.8,0.0,0.0,52,1,780,825,0.95,16,8
196772,82,15.6,18.5,1023,61,4.2,0.0,0.0,60,1,795,825,0.96,17,8
196773,51,8.0,18.5,1023,61,4.2,0.0,0.0,60,1,810,825,0.98,17,8
196774,24,2.1,18.5,1023,61,4.2,0.0,0.0,60,1,825,825,1.00,17,8
196775,0,0.0,18.5,1023,61,4.2,0.0,0.0,60,0,0,825,0.00,17,8

In [3]:
data['hour'] = np.sin(2 * np.pi * data['hour'] / 23)
data['month'] = np.sin(2 * np.pi * data['month']/12)
scaler = MinMaxScaler(feature_range = (-1, 1))
columns_to_scale = ['Energy delta[Wh]', 'GHI', 'temp', 'pressure', 'humidity', 'wind_speed', 'rain_1h', 'snow_1h', 'clouds_all', 'sunlightTime']
data[columns_to_scale] = scaler.fit_transform(data[columns_to_scale])
data

,Energy delta[Wh],GHI,temp,pressure,humidity,wind_speed,rain_1h,snow_1h,clouds_all,isSun,sunlightTime,dayLength,SunlightTime/daylength,hour,month
0,-1.000000,-1.000000,-0.305344,0.257143,1.000000,-0.314685,-1.0,-1.0,1.00,0,-1.000000,450,0.00,0.000000,0.500000
1,-1.000000,-1.000000,-0.305344,0.257143,1.000000,-0.314685,-1.0,-1.0,1.00,0,-1.000000,450,0.00,0.000000,0.500000
2,-1.000000,-1.000000,-0.305344,0.257143,1.000000,-0.314685,-1.0,-1.0,1.00,0,-1.000000,450,0.00,0.000000,0.500000
3,-1.000000,-1.000000,-0.305344,0.257143,1.000000,-0.314685,-1.0,-1.0,1.00,0,-1.000000,450,0.00,0.000000,0.500000
4,-1.000000,-1.000000,-0.301527,0.228571,1.000000,-0.272727,-1.0,-1.0,1.00,0,-1.000000,450,0.00,0.269797,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196771,-0.952988,-0.793194,0.343511,0.314286,-0.102564,-0.468531,-1.0,-1.0,0.04,1,0.529412,825,0.95,-0.942261,-0.866025
196772,-0.967331,-0.863874,0.339695,0.314286,0.000000,-0.412587,-1.0,-1.0,0.20,1,0.558824,825,0.96,-0.997669,-0.866025
196773,-0.979681,-0.930192,0.339695,0.314286,0.000000,-0.412587,-1.0,-1.0,0.20,1,0.588235,825,0.98,-0.997669,-0.866025
196774,-0.990438,-0.981675,0.339695,0.314286,0.000000,-0.412587,-1.0,-1.0,0.20,1,0.617647,825,1.00,-0.997669,-0.866025
196775,-1.000000,-1.000000,0.339695,0.314286,0.000000,-0.412587,-1.0,-1.0,0.20,0,-1.000000,825,0.00,-0.997669,-0.866025

In [28]:
features = data[:, 1:]
labels = data[:, 0]
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, shuffle=False
)
X_train.shape

(157420, 14)

In [31]:
model = Sequential([
    tf.keras.Input(shape = (14, )), 
    Dense(units = 128, activation = 'relu'),
    Dense(units = 64, activation = 'relu'),
    Dense(units = 32, activation = 'relu'),
    Dense(units = 1)
])
model.compile(optimizer = 'adam', loss = 'mse' , metrics = ['mae'])
model.fit(X_train, y_train,
            validation_data = (X_test, y_test), epochs = 100, batch_size = 32 )

Epoch 1/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 495us/step - loss: 2.6994 - mae: 0.5626 - val_loss: 0.0475 - val_mae: 0.1715
Epoch 2/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 475us/step - loss: 0.1087 - mae: 0.2430 - val_loss: 0.1191 - val_mae: 0.3106
Epoch 3/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 476us/step - loss: 0.0649 - mae: 0.1767 - val_loss: 0.0349 - val_mae: 0.1245
Epoch 4/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 479us/step - loss: 0.0345 - mae: 0.1262 - val_loss: 0.0291 - val_mae: 0.1092
Epoch 5/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 457us/step - loss: 0.0330 - mae: 0.1225 - val_loss: 0.0258 - val_mae: 0.0877
Epoch 6/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 468us/step - loss: 0.0264 - mae: 0.1049 - val_loss: 0.0272 - val_mae: 0.0980
Epoch 7/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 470us/step - loss: 0.0238 - mae: 0.0968 - val_loss: 0.0230 - val_mae: 0.0804
Epoch 8/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 464us/step - loss: 0.0223 - mae: 0.0906 - val_loss: 0.0349 - val_mae: 0.1197
Epoch 9/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 500us/step - loss: 0.0222 - mae: 0.0883 - val_loss: 0.0536 - val_mae: 0.1584
Epoch 10/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 484us/step - loss: 0.0212 - mae: 0.0832 - val_loss: 0.0210 - val_mae: 0.0745
Epoch 11/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 483us/step - loss: 0.0201 - mae: 0.0798 - val_loss: 0.0205 - val_mae: 0.0740
Epoch 12/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 518us/step - loss: 0.0199 - mae: 0.0773 - val_loss: 0.0222 - val_mae: 0.0725
Epoch 13/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 529us/step - loss: 0.0188 - mae: 0.0724 - val_loss: 0.0227 - val_mae: 0.0736
Epoch 14/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 512us/step - loss: 0.0180 - mae: 0.0686 - val_loss: 0.0194 - val_mae: 0.0646
Epoch 15/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 507us/step - loss: 0.0182 - mae: 0.0698 - val_loss: 0.0301 - val_mae: 0.1003
Epoch 16/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 503us/step - loss: 0.0186 - mae: 0.0692 - val_loss: 0.0290 - val_mae: 0.0860
Epoch 17/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 508us/step - loss: 0.0179 - mae: 0.0680 - val_loss: 0.0193 - val_mae: 0.0619
Epoch 18/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 504us/step - loss: 0.0174 - mae: 0.0670 - val_loss: 0.0199 - val_mae: 0.0649
Epoch 19/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 520us/step - loss: 0.0176 - mae: 0.0673 - val_loss: 0.0197 - val_mae: 0.0626
Epoch 20/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 538us/step - loss: 0.0171 - mae: 0.0662 - val_loss: 0.0207 - val_mae: 0.0657
Epoch 21/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 527us/step - loss: 0.0168 - mae: 0.0653 - val_loss: 0.0188 - val_mae: 0.0671
Epoch 22/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 512us/step - loss: 0.0171 - mae: 0.0662 - val_loss: 0.0241 - val_mae: 0.0771
Epoch 23/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 507us/step - loss: 0.0166 - mae: 0.0644 - val_loss: 0.0188 - val_mae: 0.0646
Epoch 24/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 524us/step - loss: 0.0166 - mae: 0.0645 - val_loss: 0.0189 - val_mae: 0.0620
Epoch 25/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 540us/step - loss: 0.0166 - mae: 0.0646 - val_loss: 0.0219 - val_mae: 0.0693
Epoch 26/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 533us/step - loss: 0.0164 - mae: 0.0640 - val_loss: 0.0217 - val_mae: 0.0725
Epoch 27/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 532us/step - loss: 0.0163 - mae: 0.0644 - val_loss: 0.0209 - val_mae: 0.0695
Epoch 28/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 536us/step - loss: 0.0164 - mae: 0.0638 - val_loss: 0.0191 - val_mae: 0.0705
Epoch 29/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 518us/step - loss: 0.0163 - mae: 0.0639 - val_loss: 0.0193 - val_mae: 0.0730
Epoch 30/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 489us/step - loss: 0.0160 - mae: 0.0633 - val_loss: 0.0190 - val_mae: 0.0699
Epoch 31/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 457us/step - loss: 0.0163 - mae: 0.0641 - val_loss: 0.0185 - val_mae: 0.0664
Epoch 32/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0160 - mae: 0.0633 - val_loss: 0.0183 - val_mae: 0.0616
Epoch 33/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 457us/step - loss: 0.0159 - mae: 0.0628 - val_loss: 0.0184 - val_mae: 0.0685
Epoch 34/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 466us/step - loss: 0.0156 - mae: 0.0622 - val_loss: 0.0192 - val_mae: 0.0632
Epoch 35/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0159 - mae: 0.0630 - val_loss: 0.0190 - val_mae: 0.0682
Epoch 36/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0157 - mae: 0.0626 - val_loss: 0.0211 - val_mae: 0.0700
Epoch 37/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 463us/step - loss: 0.0158 - mae: 0.0625 - val_loss: 0.0184 - val_mae: 0.0579
Epoch 38/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 457us/step - loss: 0.0156 - mae: 0.0614 - val_loss: 0.0185 - val_mae: 0.0659
Epoch 39/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 457us/step - loss: 0.0150 - mae: 0.0611 - val_loss: 0.0190 - val_mae: 0.0705
Epoch 40/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0155 - mae: 0.0622 - val_loss: 0.0190 - val_mae: 0.0621
Epoch 41/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 456us/step - loss: 0.0154 - mae: 0.0611 - val_loss: 0.0198 - val_mae: 0.0875
Epoch 42/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0154 - mae: 0.0616 - val_loss: 0.0204 - val_mae: 0.0697
Epoch 43/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 457us/step - loss: 0.0152 - mae: 0.0607 - val_loss: 0.0198 - val_mae: 0.0750
Epoch 44/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0150 - mae: 0.0605 - val_loss: 0.0193 - val_mae: 0.0730
Epoch 45/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0150 - mae: 0.0610 - val_loss: 0.0193 - val_mae: 0.0709
Epoch 46/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0154 - mae: 0.0606 - val_loss: 0.0185 - val_mae: 0.0582
Epoch 47/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0154 - mae: 0.0609 - val_loss: 0.0180 - val_mae: 0.0623
Epoch 48/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 461us/step - loss: 0.0150 - mae: 0.0607 - val_loss: 0.0182 - val_mae: 0.0656
Epoch 49/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 461us/step - loss: 0.0153 - mae: 0.0605 - val_loss: 0.0199 - val_mae: 0.0728
Epoch 50/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 455us/step - loss: 0.0152 - mae: 0.0602 - val_loss: 0.0179 - val_mae: 0.0624
Epoch 51/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 457us/step - loss: 0.0152 - mae: 0.0609 - val_loss: 0.0189 - val_mae: 0.0630
Epoch 52/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 467us/step - loss: 0.0153 - mae: 0.0607 - val_loss: 0.0181 - val_mae: 0.0655
Epoch 53/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 453us/step - loss: 0.0154 - mae: 0.0605 - val_loss: 0.0198 - val_mae: 0.0608
Epoch 54/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 466us/step - loss: 0.0151 - mae: 0.0598 - val_loss: 0.0180 - val_mae: 0.0576
Epoch 55/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 514us/step - loss: 0.0153 - mae: 0.0602 - val_loss: 0.0199 - val_mae: 0.0707
Epoch 56/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 493us/step - loss: 0.0149 - mae: 0.0587 - val_loss: 0.0177 - val_mae: 0.0622
Epoch 57/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 3s 514us/step - loss: 0.0148 - mae: 0.0592 - val_loss: 0.0178 - val_mae: 0.0599
Epoch 58/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 501us/step - loss: 0.0150 - mae: 0.0589 - val_loss: 0.0174 - val_mae: 0.0583
Epoch 59/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 498us/step - loss: 0.0149 - mae: 0.0585 - val_loss: 0.0198 - val_mae: 0.0621
Epoch 60/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 481us/step - loss: 0.0147 - mae: 0.0588 - val_loss: 0.0196 - val_mae: 0.0640
Epoch 61/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 486us/step - loss: 0.0149 - mae: 0.0590 - val_loss: 0.0195 - val_mae: 0.0670
Epoch 62/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 478us/step - loss: 0.0146 - mae: 0.0586 - val_loss: 0.0181 - val_mae: 0.0623
Epoch 63/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 472us/step - loss: 0.0148 - mae: 0.0588 - val_loss: 0.0177 - val_mae: 0.0616
Epoch 64/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 473us/step - loss: 0.0148 - mae: 0.0586 - val_loss: 0.0172 - val_mae: 0.0571
Epoch 65/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 481us/step - loss: 0.0150 - mae: 0.0586 - val_loss: 0.0182 - val_mae: 0.0616
Epoch 66/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 472us/step - loss: 0.0151 - mae: 0.0587 - val_loss: 0.0177 - val_mae: 0.0602
Epoch 67/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 461us/step - loss: 0.0148 - mae: 0.0581 - val_loss: 0.0187 - val_mae: 0.0671
Epoch 68/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0146 - mae: 0.0577 - val_loss: 0.0196 - val_mae: 0.0705
Epoch 69/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 468us/step - loss: 0.0146 - mae: 0.0584 - val_loss: 0.0183 - val_mae: 0.0647
Epoch 70/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 488us/step - loss: 0.0148 - mae: 0.0588 - val_loss: 0.0203 - val_mae: 0.0734
Epoch 71/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 482us/step - loss: 0.0146 - mae: 0.0577 - val_loss: 0.0186 - val_mae: 0.0596
Epoch 72/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 477us/step - loss: 0.0148 - mae: 0.0584 - val_loss: 0.0171 - val_mae: 0.0618
Epoch 73/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 479us/step - loss: 0.0148 - mae: 0.0585 - val_loss: 0.0178 - val_mae: 0.0597
Epoch 74/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 469us/step - loss: 0.0149 - mae: 0.0588 - val_loss: 0.0192 - val_mae: 0.0696
Epoch 75/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 461us/step - loss: 0.0146 - mae: 0.0575 - val_loss: 0.0182 - val_mae: 0.0645
Epoch 76/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0149 - mae: 0.0591 - val_loss: 0.0175 - val_mae: 0.0621
Epoch 77/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0146 - mae: 0.0580 - val_loss: 0.0179 - val_mae: 0.0604
Epoch 78/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0147 - mae: 0.0585 - val_loss: 0.0185 - val_mae: 0.0636
Epoch 79/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0148 - mae: 0.0585 - val_loss: 0.0173 - val_mae: 0.0633
Epoch 80/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 470us/step - loss: 0.0144 - mae: 0.0568 - val_loss: 0.0202 - val_mae: 0.0638
Epoch 81/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 467us/step - loss: 0.0146 - mae: 0.0577 - val_loss: 0.0192 - val_mae: 0.0627
Epoch 82/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0147 - mae: 0.0579 - val_loss: 0.0176 - val_mae: 0.0573
Epoch 83/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 459us/step - loss: 0.0148 - mae: 0.0579 - val_loss: 0.0192 - val_mae: 0.0684
Epoch 84/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 472us/step - loss: 0.0144 - mae: 0.0576 - val_loss: 0.0182 - val_mae: 0.0638
Epoch 85/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 488us/step - loss: 0.0148 - mae: 0.0578 - val_loss: 0.0194 - val_mae: 0.0705
Epoch 86/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 477us/step - loss: 0.0145 - mae: 0.0567 - val_loss: 0.0181 - val_mae: 0.0622
Epoch 87/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 475us/step - loss: 0.0144 - mae: 0.0575 - val_loss: 0.0176 - val_mae: 0.0576
Epoch 88/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 477us/step - loss: 0.0143 - mae: 0.0568 - val_loss: 0.0172 - val_mae: 0.0599
Epoch 89/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 473us/step - loss: 0.0147 - mae: 0.0576 - val_loss: 0.0180 - val_mae: 0.0712
Epoch 90/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 459us/step - loss: 0.0144 - mae: 0.0577 - val_loss: 0.0193 - val_mae: 0.0687
Epoch 91/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 459us/step - loss: 0.0148 - mae: 0.0584 - val_loss: 0.0174 - val_mae: 0.0575
Epoch 92/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0144 - mae: 0.0566 - val_loss: 0.0174 - val_mae: 0.0656
Epoch 93/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 459us/step - loss: 0.0145 - mae: 0.0580 - val_loss: 0.0179 - val_mae: 0.0622
Epoch 94/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0144 - mae: 0.0569 - val_loss: 0.0174 - val_mae: 0.0612
Epoch 95/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0145 - mae: 0.0576 - val_loss: 0.0182 - val_mae: 0.0590
Epoch 96/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0147 - mae: 0.0580 - val_loss: 0.0170 - val_mae: 0.0633
Epoch 97/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 459us/step - loss: 0.0144 - mae: 0.0573 - val_loss: 0.0182 - val_mae: 0.0660
Epoch 98/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 460us/step - loss: 0.0146 - mae: 0.0577 - val_loss: 0.0169 - val_mae: 0.0583
Epoch 99/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 461us/step - loss: 0.0145 - mae: 0.0581 - val_loss: 0.0172 - val_mae: 0.0644
Epoch 100/100
4920/4920 ━━━━━━━━━━━━━━━━━━━━ 2s 458us/step - loss: 0.0149 - mae: 0.0577 - val_loss: 0.0190 - val_mae: 0.0667